# Generated by Django 2.1.7 on 2019-03-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpDeparture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.IntegerField()),
                ('scheduled_time', models.DateTimeField(null=True, verbose_name='scheduled time')),
                ('real_time', models.DateTimeField(null=True, verbose_name='real time')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='miner.Line')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='miner.Stop')),
            ],
        ),
    ]
